### ISSUE TITLE
Unable to install following README

### ISSUE THREAD

**Issue by jschwab** [starkit/starkit#30]
I have attempted to install starkit by following the instructions in the README.  I am using conda on OS X 10.12.6.

I successfully created and activated a starkit environment.  However, when I run

`pip install git+https://github.com/starkit/starkit`

I receive the following error message.

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting git+https://github.com/starkit/starkit
  Cloning https://github.com/starkit/starkit to /private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4
    Complete output from command python setup.py egg_info:
    [[1mpy.warnings         [0m][[1;33mWARNING[0m]  /private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4/astropy_helpers/astropy_helpers/setup_helpers.py:102: AstropyDeprecationWarning: Direct use of the adjust_compiler function in setup.py is deprecated and can be removed from your setup.py.  This functionality is now incorporated directly into the build_ext command.
      'command.', AstropyDeprecationWarning)
     ([1msetup_helpers.py[0m:102)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4/setup.py", line 65, in <module>
        get_debug_option(PACKAGENAME))
      File "/private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4/astropy_helpers/astropy_helpers/setup_helpers.py", line 125, in get_debug_option
        if any(cmd in dist.commands for cmd in ['build', 'build_ext']):
      File "/private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4/astropy_helpers/astropy_helpers/setup_helpers.py", line 125, in <genexpr>
        if any(cmd in dist.commands for cmd in ['build', 'build_ext']):
    AttributeError: Distribution instance has no attribute 'commands'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/td/_g_smy014tg9t8zpw90tylyr0000gp/T/pip-req-build-b_QB_4/
```

**Comment by jschwab** [comment]
If I try to follow the full development instructions, then running

`python setup.py develop`

gives the error

```Initializing astropy_helpers submodule with: `git submodule update --init -- astropy_helpers`
[[1mpy.warnings         [0m][[1;33mWARNING[0m]  /Users/jschwab/Research/starkit-dev/astropy_helpers/astropy_helpers/setup_helpers.py:102: AstropyDeprecationWarning: Direct use of the adjust_compiler function in setup.py is deprecated and can be removed from your setup.py.  This functionality is now incorporated directly into the build_ext command.
  'command.', AstropyDeprecationWarning)
 ([1msetup_helpers.py[0m:102)
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    get_debug_option(PACKAGENAME))
  File "/Users/jschwab/Research/starkit-dev/astropy_helpers/astropy_helpers/setup_helpers.py", line 125, in get_debug_option
    if any(cmd in dist.commands for cmd in ['build', 'build_ext']):
  File "/Users/jschwab/Research/starkit-dev/astropy_helpers/astropy_helpers/setup_helpers.py", line 125, in <genexpr>
    if any(cmd in dist.commands for cmd in ['build', 'build_ext']):
AttributeError: Distribution instance has no attribute 'commands'
```

Then if I run `python setup.py develop` a second time, things appear to work

After doing that and then taking the same "clone the git and try twice" approach for wysnphot, I think I got them installed.

**Comment by wkerzendorf** [comment]
@jschwab did you setup a new python environment up with miniconda?

**Comment by wkerzendorf** [comment]
did you activate your environment by doing source activate starkit?

**Comment by jschwab** [comment]
I'm away from the computer that I did this on, but before the problem with `pip install`, I installed anaconda and then did

```
curl -O https://raw.githubusercontent.com/starkit/starkit/master/starkit_env27.yml
conda env create --file starkit_env27.yml -n starkit
```
and then did

```
conda activate starkit
```

I don't think `source activate` makes sense with the conda env. (To me `source` harkens back to the virtualenv days.)

That suspected conda/source typo is in part what #29 is about.

**Comment by jschwab** [comment]
I just reproduced this same issue on my Linux machine.  In this case:

```
(starkit) monolith: ~$ which python
/home/jschwab/.conda/envs/starkit/bin/python
(starkit) monolith: ~$ which pip
/home/jschwab/.conda/envs/starkit/bin/pip
```

**Comment by 97amarnathk** [comment]
I am also facing the same issue when building on Travis CI.
